import { AnalyticsMetrics, EnrichedTransaction } from '../types/client';

export const INITIAL_MOCK_METRICS: AnalyticsMetrics = {
  total_failed_count: 8,
  total_failed_volume_in_paise: 960800,
  total_recovered_count: 6,
  total_recovered_volume_in_paise: 754300,
  business_decline_count: 7,
  business_decline_recovery_rate_pct: 78.5,
  overall_recovery_rate_pct: 75.0,
  avg_recovery_latency_minutes: 14.5,
  channel_conversion_lift: {
    whatsapp_conversion_pct: 84,
    sms_conversion_pct: 62,
    raw_checkout_conversion_pct: 31,
  },
  decline_code_breakdown: {
    'U30': 3,
    'ZM': 2,
    'XB': 2,
    'ZA': 1,
  },
};

export const INITIAL_MOCK_TRANSACTIONS: EnrichedTransaction[] = [
  {
    id: 'txn_seed_1000',
    user_id: 'usr_seed_1',
    merchant_id: 'merch_swiggyinstamart',
    merchant_name: 'Swiggy Instamart',
    amount_in_paise: 54900,
    currency: 'INR',
    order_id: 'ORD-REC-7890',
    razorpay_payment_id: 'pay_seed_9fa8710b12',
    status: 'recovered',
    payment_method: 'upi_intent',
    created_at: new Date(Date.now() - 3600000).toISOString(),
    updated_at: new Date().toISOString(),
    user: {
      id: 'usr_seed_1',
      name: 'Rahul Sharma',
      email: 'rahul.s@gmail.com',
      phone: '+919876543210',
      upi_id: 'rahul@okhdfcbank',
      historical_orders_count: 12,
      historical_success_rate: 0.94,
      created_at: new Date(Date.now() - 86400000).toISOString(),
      updated_at: new Date().toISOString(),
    },
    failure_event: {
      id: 'fail_seed_1',
      transaction_id: 'txn_seed_1000',
      error_code: 'BAD_REQUEST_ERROR',
      upi_decline_code: 'ZM',
      error_description: 'Invalid UPI PIN entered by user',
      error_source: 'customer',
      error_step: 'payment_authorization',
      occurred_at: new Date(Date.now() - 3600000).toISOString(),
    },
    prediction: {
      id: 'pred_seed_1',
      transaction_id: 'txn_seed_1000',
      is_recoverable: true,
      decline_type: 'BUSINESS_DECLINE',
      confidence_score: 0.96,
      recommended_strategy: 'INSTANT_PAYMENT_LINK',
      optimal_retry_delay_seconds: 300,
      predicted_optimal_time: new Date(Date.now() - 3300000).toISOString(),
      feature_signals: {
        decline_code_weight: 0.95,
        customer_loyalty_boost: 0.15,
        amount_sensitivity_factor: 0.1,
        hour_of_day_penalty: 0,
      },
      created_at: new Date(Date.now() - 3600000).toISOString(),
      explanation: 'Wrong PIN is a high-intent momentary slip. Customer immediately recovers via a 1-tap pre-filled checkout link.',
      timing_rationale: 'Instant 5-minute link window yields maximum recovery before customer abandons order.',
    },
    nudges: [
      {
        id: 'ndg_seed_1',
        transaction_id: 'txn_seed_1000',
        prediction_id: 'pred_seed_1',
        channel: 'whatsapp',
        recipient_phone: '+919876543210',
        message_content: 'Hey Rahul! 👋\n\nThere was a quick PIN mismatch on your UPI app for ₹549 at *Swiggy Instamart*.\n\nYour cart is saved! Tap here to complete in 1 click:\n👉 https://rzp.io/i/sw7890\n\n_Secure payment powered by Razorpay_',
        razorpay_payment_link_id: 'plink_seed_sw7890',
        razorpay_payment_link_url: 'https://rzp.io/i/sw7890',
        status: 'recovered',
        scheduled_for: new Date(Date.now() - 3300000).toISOString(),
        created_at: new Date(Date.now() - 3600000).toISOString(),
      },
    ],
  },
  {
    id: 'txn_seed_1001',
    user_id: 'usr_seed_2',
    merchant_id: 'merch_zomatogold',
    merchant_name: 'Zomato Gold',
    amount_in_paise: 89900,
    currency: 'INR',
    order_id: 'ORD-REC-7891',
    razorpay_payment_id: 'pay_seed_34ad910c22',
    status: 'recovered',
    payment_method: 'upi_intent',
    created_at: new Date(Date.now() - 7200000).toISOString(),
    updated_at: new Date().toISOString(),
    user: {
      id: 'usr_seed_2',
      name: 'Priya Patel',
      email: 'priya.p@outlook.com',
      phone: '+919812345678',
      upi_id: 'priya@icici',
      historical_orders_count: 8,
      historical_success_rate: 0.91,
      created_at: new Date(Date.now() - 86400000).toISOString(),
      updated_at: new Date().toISOString(),
    },
    failure_event: {
      id: 'fail_seed_2',
      transaction_id: 'txn_seed_1001',
      error_code: 'BAD_REQUEST_ERROR',
      upi_decline_code: 'U30',
      error_description: 'Insufficient balance in bank account',
      error_source: 'customer',
      error_step: 'payment_authorization',
      occurred_at: new Date(Date.now() - 7200000).toISOString(),
    },
    prediction: {
      id: 'pred_seed_2',
      transaction_id: 'txn_seed_1001',
      is_recoverable: true,
      decline_type: 'BUSINESS_DECLINE',
      confidence_score: 0.92,
      recommended_strategy: 'TIMED_RECOVERY_NUDGE',
      optimal_retry_delay_seconds: 3600,
      predicted_optimal_time: new Date(Date.now() - 3600000).toISOString(),
      feature_signals: {
        decline_code_weight: 0.88,
        customer_loyalty_boost: 0.1,
        amount_sensitivity_factor: 0.05,
        hour_of_day_penalty: 0,
      },
      created_at: new Date(Date.now() - 7200000).toISOString(),
      explanation: 'Insufficient balance requires funding window or alternative UPI account/card.',
      timing_rationale: 'Scheduled after 1 hour allowing customer to transfer funds without being intrusive.',
    },
    nudges: [
      {
        id: 'ndg_seed_2',
        transaction_id: 'txn_seed_1001',
        prediction_id: 'pred_seed_2',
        channel: 'whatsapp',
        recipient_phone: '+919812345678',
        message_content: 'Hi Priya! 👋\n\nYour ₹899 order at *Zomato Gold* had a brief bank balance mismatch.\n\nYou can retry with another account or card here:\n👉 https://rzp.io/i/zm8991\n\n_Secure checkout powered by Razorpay_',
        razorpay_payment_link_id: 'plink_seed_zm8991',
        razorpay_payment_link_url: 'https://rzp.io/i/zm8991',
        status: 'recovered',
        scheduled_for: new Date(Date.now() - 3600000).toISOString(),
        created_at: new Date(Date.now() - 7200000).toISOString(),
      },
    ],
  },
  {
    id: 'txn_seed_1002',
    user_id: 'usr_seed_3',
    merchant_id: 'merch_blinkit',
    merchant_name: 'Blinkit',
    amount_in_paise: 38500,
    currency: 'INR',
    order_id: 'ORD-REC-7892',
    razorpay_payment_id: 'pay_seed_11ff22aa33',
    status: 'recovered',
    payment_method: 'upi_intent',
    created_at: new Date(Date.now() - 10800000).toISOString(),
    updated_at: new Date().toISOString(),
    user: {
      id: 'usr_seed_3',
      name: 'Ananya Verma',
      email: 'ananya.v@gmail.com',
      phone: '+919899123456',
      upi_id: 'ananya@paytm',
      historical_orders_count: 5,
      historical_success_rate: 0.88,
      created_at: new Date(Date.now() - 86400000).toISOString(),
      updated_at: new Date().toISOString(),
    },
    failure_event: {
      id: 'fail_seed_3',
      transaction_id: 'txn_seed_1002',
      error_code: 'BAD_REQUEST_ERROR',
      upi_decline_code: 'XB',
      error_description: 'Customer checkout session interrupted',
      error_source: 'customer',
      error_step: 'payment_authorization',
      occurred_at: new Date(Date.now() - 10800000).toISOString(),
    },
    prediction: {
      id: 'pred_seed_3',
      transaction_id: 'txn_seed_1002',
      is_recoverable: true,
      decline_type: 'BUSINESS_DECLINE',
      confidence_score: 0.89,
      recommended_strategy: 'ABANDONED_CART_DISCOUNT_NUDGE',
      optimal_retry_delay_seconds: 1200,
      predicted_optimal_time: new Date(Date.now() - 9600000).toISOString(),
      feature_signals: {
        decline_code_weight: 0.85,
        customer_loyalty_boost: 0.08,
        amount_sensitivity_factor: 0.12,
        hour_of_day_penalty: 0,
      },
      created_at: new Date(Date.now() - 10800000).toISOString(),
      explanation: 'User abandoned payment screen. Fast WhatsApp nudge recovers lost intent.',
      timing_rationale: '20-minute gentle reminder restores interrupted grocery cart.',
    },
    nudges: [
      {
        id: 'ndg_seed_3',
        transaction_id: 'txn_seed_1002',
        prediction_id: 'pred_seed_3',
        channel: 'whatsapp',
        recipient_phone: '+919899123456',
        message_content: 'Hey Ananya! 👋\n\nYour ₹385 grocery bag at *Blinkit* is waiting for you.\n\nTap to complete delivery in 1 click:\n👉 https://rzp.io/i/bl3852',
        razorpay_payment_link_id: 'plink_seed_bl3852',
        razorpay_payment_link_url: 'https://rzp.io/i/bl3852',
        status: 'recovered',
        scheduled_for: new Date(Date.now() - 9600000).toISOString(),
        created_at: new Date(Date.now() - 10800000).toISOString(),
      },
    ],
  },
  {
    id: 'txn_seed_1003',
    user_id: 'usr_seed_4',
    merchant_id: 'merch_flipkart',
    merchant_name: 'Flipkart',
    amount_in_paise: 349900,
    currency: 'INR',
    order_id: 'ORD-REC-7893',
    razorpay_payment_id: 'pay_seed_44cc88ee99',
    status: 'failed',
    payment_method: 'upi_intent',
    created_at: new Date(Date.now() - 14400000).toISOString(),
    updated_at: new Date().toISOString(),
    user: {
      id: 'usr_seed_4',
      name: 'Vikram Malhotra',
      email: 'vikram.m@gmail.com',
      phone: '+919711223344',
      upi_id: 'vikram@oksbi',
      historical_orders_count: 20,
      historical_success_rate: 0.95,
      created_at: new Date(Date.now() - 86400000).toISOString(),
      updated_at: new Date().toISOString(),
    },
    failure_event: {
      id: 'fail_seed_4',
      transaction_id: 'txn_seed_1003',
      error_code: 'BAD_REQUEST_ERROR',
      upi_decline_code: 'U28',
      error_description: 'Daily UPI transaction limit exceeded',
      error_source: 'customer',
      error_step: 'payment_authorization',
      occurred_at: new Date(Date.now() - 14400000).toISOString(),
    },
    prediction: {
      id: 'pred_seed_4',
      transaction_id: 'txn_seed_1003',
      is_recoverable: true,
      decline_type: 'BUSINESS_DECLINE',
      confidence_score: 0.94,
      recommended_strategy: 'NEXT_DAY_RESET_NUDGE',
      optimal_retry_delay_seconds: 36000,
      predicted_optimal_time: new Date(Date.now() + 18000000).toISOString(),
      feature_signals: {
        decline_code_weight: 0.92,
        customer_loyalty_boost: 0.2,
        amount_sensitivity_factor: -0.05,
        hour_of_day_penalty: 0,
      },
      created_at: new Date(Date.now() - 14400000).toISOString(),
      explanation: 'Daily UPI limit exceeded. Auto-scheduled for next morning 8:30 AM when bank NPCI limit resets.',
      timing_rationale: 'Scheduled for 8:30 AM following morning after NPCI cumulative debit limit resets.',
    },
    nudges: [
      {
        id: 'ndg_seed_4',
        transaction_id: 'txn_seed_1003',
        prediction_id: 'pred_seed_4',
        channel: 'whatsapp',
        recipient_phone: '+919711223344',
        message_content: 'Good morning Vikram! ☀️\n\nYour UPI daily limit has refreshed. Your ₹3,499 order at *Flipkart* is reserved.\n\nTap below to complete in 1 click:\n👉 https://rzp.io/i/fk3499',
        razorpay_payment_link_id: 'plink_seed_fk3499',
        razorpay_payment_link_url: 'https://rzp.io/i/fk3499',
        status: 'queued',
        scheduled_for: new Date(Date.now() + 18000000).toISOString(),
        created_at: new Date(Date.now() - 14400000).toISOString(),
      },
    ],
  },
  {
    id: 'txn_seed_1004',
    user_id: 'usr_seed_5',
    merchant_id: 'merch_zepto',
    merchant_name: 'Zepto Daily',
    amount_in_paise: 72000,
    currency: 'INR',
    order_id: 'ORD-REC-7894',
    razorpay_payment_id: 'pay_seed_55aa11bb88',
    status: 'failed',
    payment_method: 'upi_intent',
    created_at: new Date(Date.now() - 18000000).toISOString(),
    updated_at: new Date().toISOString(),
    user: {
      id: 'usr_seed_5',
      name: 'Sneha Kulkarni',
      email: 'sneha.k@yahoo.com',
      phone: '+919988776655',
      upi_id: 'sneha@axisbank',
      historical_orders_count: 2,
      historical_success_rate: 0.75,
      created_at: new Date(Date.now() - 86400000).toISOString(),
      updated_at: new Date().toISOString(),
    },
    failure_event: {
      id: 'fail_seed_5',
      transaction_id: 'txn_seed_1004',
      error_code: 'BAD_REQUEST_ERROR',
      upi_decline_code: 'ZA',
      error_description: 'Dormant or frozen bank account',
      error_source: 'customer',
      error_step: 'payment_authorization',
      occurred_at: new Date(Date.now() - 18000000).toISOString(),
    },
    prediction: {
      id: 'pred_seed_5',
      transaction_id: 'txn_seed_1004',
      is_recoverable: false,
      decline_type: 'TECHNICAL_DECLINE',
      confidence_score: 0.12,
      recommended_strategy: 'NO_ACTION_TECHNICAL_ERROR',
      optimal_retry_delay_seconds: 0,
      predicted_optimal_time: new Date(Date.now() - 18000000).toISOString(),
      feature_signals: {
        decline_code_weight: 0.1,
        customer_loyalty_boost: 0,
        amount_sensitivity_factor: 0,
        hour_of_day_penalty: 0,
      },
      created_at: new Date(Date.now() - 18000000).toISOString(),
      explanation: 'Dormant account is a non-recoverable hard decline. Automated spam nudges suppressed.',
      timing_rationale: 'No nudges sent to protect brand reputation from spamming unrecoverable accounts.',
    },
    nudges: [],
  },
];
